# Generated by Django 5.1.3 on 2024-11-15 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bstudents',
            fields=[
                ('student_id', models.IntegerField(default='sid', primary_key=True, serialize=False, unique=True)),
                ('student_name', models.CharField(default='sid', max_length=50)),
                ('level', models.IntegerField()),
                ('student_email', models.EmailField(default='email', max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('course_name', models.CharField(max_length=50)),
                ('descrpition', models.TextField()),
                ('total_class', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('enrollment_date', models.DateField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_edge.courses')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_edge.bstudents')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('instructor_id', models.AutoField(primary_key=True, serialize=False)),
                ('instructor_name', models.TextField()),
                ('instructor_email', models.EmailField(max_length=254, unique=True)),
                ('course_taken', models.ForeignKey(default='couse_name', on_delete=django.db.models.deletion.CASCADE, to='app_edge.courses')),
            ],
        ),
    ]
