# Generated by Django 5.1.3 on 2024-11-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bstudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sid', models.IntegerField()),
                ('level', models.IntegerField()),
                ('enrolled', models.CharField(max_length=50)),
                ('batch_code', models.CharField(max_length=50)),
                ('ongoing', models.BooleanField(default=True)),
            ],
        ),
    ]
