# Generated by Django 5.1.3 on 2024-11-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_edge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentEnrollment',
            fields=[
                ('senrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=100)),
                ('sid', models.CharField(max_length=150)),
                ('level', models.IntegerField()),
                ('semail', models.EmailField(max_length=254)),
                ('enroll_for', models.CharField(max_length=150)),
                ('course_code', models.CharField(max_length=50)),
            ],
        ),
    ]
